# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af8ca207f6fec122f9ceafcab79e1cd949ee211240a20eb5d7f6da8c4948251582225cc4ebe45402f5f3fe758a9444d71e6cebbfdd521e54340b0e1a8733f715

test:
  secret_key_base: 573a3a455c02df689f22531bbb910a1a4d0ee384cf991509944e3f3310936abc077403cae7edce5c1fbd03126699fde31a5f59e0f85465d8f296ca4859829f0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
